import smtplib
import subprocess
import os
from collections import Counter
from email.mime.text import MIMEText
from datetime import datetime, timezone, timedelta

SENDER_EMAIL = os.environ['EMAIL_USERNAME']


# ── Ordinal suffix helper (1st, 2nd, 3rd, 4th ...) ────────────────────────────
def ordinal(n):
    if 11 <= (n % 100) <= 13:
        suffix = 'th'
    else:
        suffix = {1: 'st', 2: 'nd', 3: 'rd'}.get(n % 10, 'th')
    return f"{n}{suffix}"


def fmt_date(dt):
    return f"{ordinal(dt.day)} {dt.strftime('%B %Y')}"


# ── Git helper ─────────────────────────────────────────────────────────────────
def git(cmd):
    return subprocess.run(
        cmd, shell=True, capture_output=True, text=True
    ).stdout.strip()


# ── Date range ─────────────────────────────────────────────────────────────────
now         = datetime.now(timezone.utc)
since       = now - timedelta(days=7)
since_iso   = since.strftime('%Y-%m-%dT%H:%M:%SZ')
date_from   = fmt_date(since)
date_to     = fmt_date(now)
week_label  = f"{date_from} to {date_to}"
report_date = fmt_date(now)
repo_name   = os.environ['REPO_NAME']

# ── Raw commits (--no-merges keeps counts meaningful) ─────────────────────────
raw     = git(f'git log --no-merges --after="{since_iso}" --format="%an|%s"')
commits = [line for line in raw.splitlines() if line.strip()]

# ── All-time authors ───────────────────────────────────────────────────────────
all_authors = sorted(set(
    a for a in git('git log --no-merges --format="%an"').splitlines() if a.strip()
))

DIVIDER = "=" * 52
SECTION = "-" * 36

# ── Edge case: no commits ──────────────────────────────────────────────────────
if not commits:
    body = (
        "Respected Ma'am,\n\n"
        "Thank you for your guidance and support this week. "
        "As per your suggestions, please find the automated weekly progress report below:\n\n"
        f"{DIVIDER}\n"
        "  WEEKLY GITHUB CONTRIBUTION REPORT\n"
        f"  Sent by    : {SENDER_EMAIL}\n"
        f"  Repository : {repo_name}\n"
        f"  Report for : {date_from} to {date_to}\n"
        f"  Generated  : {report_date}\n"
        f"{DIVIDER}\n\n"
        f"No commits were made from {date_from} to {date_to}.\n\n"
        f"{DIVIDER}\n"
        "This is an automated report generated by GitHub Actions.\n"
        "Workflow : PW26_MG_02_AUTOUPDATES_WEEKLY"
    )
    subject = (
        f"[PW26_MG_02] Weekly Report | {week_label}"
        " | 0 Commits | ALL MEMBERS INACTIVE"
    )

else:
    # ── Summary ───────────────────────────────────────────────────────────────
    total_commits  = len(commits)
    active_set     = set(c.split('|', 1)[0] for c in commits if c.strip())
    active_authors = sorted(active_set)
    active_count   = len(active_authors)

    # ── Ranking ───────────────────────────────────────────────────────────────
    counts        = Counter(c.split('|', 1)[0] for c in commits if c.strip())
    ranking_lines = "\n".join(
        f"  {author} -> {n} commit(s)"
        for author, n in counts.most_common()
    )

    # ── Inactive members ──────────────────────────────────────────────────────
    inactive_authors = [a for a in all_authors if a not in active_set]
    inactive_count   = len(inactive_authors)

    if inactive_authors:
        inactive_lines = "\n".join(f"  - {a}" for a in inactive_authors)
        inactive_names = ", ".join(inactive_authors)
    else:
        inactive_lines = "  All contributors were active this week."
        inactive_names = "None"

    # ── Recent commits (last 10) ──────────────────────────────────────────────
    recent_lines = "\n".join(
        f"  {parts[0]}: {parts[1] if len(parts) > 1 else '(no message)'}"
        for c in commits[:10]
        for parts in [c.split('|', 1)]
    )

    # ── Assemble body ─────────────────────────────────────────────────────────
    body = (
        "Respected Ma'am,\n\n"
        "Thank you for your guidance and support this week. "
        "As per your suggestions, please find the automated weekly progress report below:\n\n"
        f"{DIVIDER}\n"
        "  WEEKLY GITHUB CONTRIBUTION REPORT\n"
        f"  Sent by    : {SENDER_EMAIL}\n"
        f"  Repository : {repo_name}\n"
        f"  Report for : {date_from} to {date_to}\n"
        f"  Generated  : {report_date}\n"
        f"{DIVIDER}\n\n"
        f"{SECTION}\n"
        "[A] SUMMARY\n"
        f"{SECTION}\n"
        f"  Report covers               : {date_from} to {date_to}\n"
        f"  Total commits (last 7 days) : {total_commits}\n"
        f"  Active contributors         : {active_count}\n"
        f"  Inactive contributors       : {inactive_count}\n\n"
        f"{SECTION}\n"
        "[B] CONTRIBUTION RANKING\n"
        f"{SECTION}\n"
        f"{ranking_lines}\n\n"
        f"{SECTION}\n"
        "[C] INACTIVE MEMBERS (0 commits this week)\n"
        f"{SECTION}\n"
        f"{inactive_lines}\n\n"
        f"{SECTION}\n"
        "[D] RECENT COMMITS (last 10)\n"
        f"{SECTION}\n"
        f"{recent_lines}\n\n"
        f"{DIVIDER}\n"
        "This is an automated report generated by GitHub Actions.\n"
        "Workflow : PW26_MG_02_AUTOUPDATES_WEEKLY"
    )

    # ── Subject ───────────────────────────────────────────────────────────────
    if inactive_names == "None":
        subject = (
            f"[PW26_MG_02] Weekly Report | {week_label}"
            f" | {total_commits} Commits | All {active_count} Members Active"
        )
    else:
        MAX_SUBJECT_INACTIVE = 60
        inactive_label = inactive_names
        if len(inactive_names) > MAX_SUBJECT_INACTIVE:
            inactive_label = (
                inactive_names[:MAX_SUBJECT_INACTIVE].rsplit(", ", 1)[0] + ", ..."
            )
        subject = (
            f"[PW26_MG_02] Weekly Report | {week_label}"
            f" | {total_commits} Commits | Inactive: {inactive_label}"
        )

# ── Send email ─────────────────────────────────────────────────────────────────
username   = os.environ['EMAIL_USERNAME']
password   = os.environ['EMAIL_PASSWORD']
recipients = [
    'mahitha.g@pes.edu',
    'mahitharesearch@gmail.com',
    'mailtoadishreegupta@gmail.com',
]

msg = MIMEText(body, 'plain', 'utf-8')
msg['Subject'] = subject
msg['From']    = f'PW26_MG_02_AUTOUPDATES_WEEKLY <{SENDER_EMAIL}>'
msg['To']      = ', '.join(recipients)

with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
    smtp.login(username, password)
    smtp.sendmail(SENDER_EMAIL, recipients, msg.as_string())

print("Email sent successfully.")
print(f"From    : {SENDER_EMAIL}")
print(f"Subject : {subject}")
