#!/usr/bin/env python3
"""
Emotion Propagation Graph Neural Network (EP-GNN) - Data Model & Feature Engineering Engine
Defines data schemas, validation logic, and feature computation
for the data generation pipeline.
"""

import numpy as np
import pandas as pd
import json
import os
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Any, Optional, Tuple
from datetime import datetime
import hashlib

# ──────────────────────────────────────────────────────────────────────────────
# DATA CLASSES / SCHEMAS
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class AssetRecord:
    """Represents a single financial asset with all associated metadata."""
    asset_id: str
    sector: str
    market_cap_tier: str          # "small", "mid", "large"
    exchange: str
    listing_date: str
    primary_currency: str = "USD"
    is_active: bool = True
    manipulation_risk_prior: float = 0.0

    def to_neo4j_props(self) -> dict:
        return {
            "assetId": self.asset_id,
            "sector": self.sector,
            "marketCapTier": self.market_cap_tier,
            "exchange": self.exchange,
            "listingDate": self.listing_date,
            "currency": self.primary_currency,
            "isActive": self.is_active,
            "manipulationRiskPrior": self.manipulation_risk_prior,
        }


@dataclass
class MarketRegimeRecord:
    """Represents a detected market regime window."""
    regime_id: str
    regime_type: str
    start_timestamp: str
    end_timestamp: str
    confidence: float
    asset_id: str
    avg_volatility: float
    avg_volume: float
    trend_direction: str   # "up", "down", "flat"

    def to_neo4j_props(self) -> dict:
        return {
            "regimeId": self.regime_id,
            "regimeType": self.regime_type,
            "startTime": self.start_timestamp,
            "endTime": self.end_timestamp,
            "confidence": self.confidence,
            "assetId": self.asset_id,
            "avgVolatility": self.avg_volatility,
            "avgVolume": self.avg_volume,
            "trendDirection": self.trend_direction,
        }


@dataclass
class SignalRecord:
    """Represents a manipulation signal detected in the data."""
    signal_id: str
    signal_type: str      # "price_spike", "volume_surge", "sentiment_burst", etc.
    asset_id: str
    timestamp: str
    strength: float       # 0–1
    confidence: float     # 0–1
    features: Dict[str, float] = field(default_factory=dict)

    def to_neo4j_props(self) -> dict:
        props = {
            "signalId": self.signal_id,
            "signalType": self.signal_type,
            "assetId": self.asset_id,
            "timestamp": self.timestamp,
            "strength": self.strength,
            "confidence": self.confidence,
        }
        props.update({f"feature_{k}": v for k, v in self.features.items()})
        return props


@dataclass
class InfluencerRecord:
    """Represents a social media influencer / news source."""
    influencer_id: str
    platform: str
    follower_count: int
    influencer_type: str   # "bot", "retail", "institutional", etc.
    avg_sentiment: float
    post_count: int
    engagement_rate: float
    is_suspicious: bool = False

    def to_neo4j_props(self) -> dict:
        return {
            "influencerId": self.influencer_id,
            "platform": self.platform,
            "followerCount": self.follower_count,
            "influencerType": self.influencer_type,
            "avgSentiment": self.avg_sentiment,
            "postCount": self.post_count,
            "engagementRate": self.engagement_rate,
            "isSuspicious": self.is_suspicious,
        }


@dataclass
class RiskAlertRecord:
    """Represents a manipulation risk alert generated by the system."""
    alert_id: str
    asset_id: str
    alert_type: str
    severity: str          # "low", "medium", "high", "critical"
    risk_score: float
    timestamp: str
    description: str
    supporting_signals: List[str] = field(default_factory=list)
    acknowledged: bool = False

    def to_neo4j_props(self) -> dict:
        return {
            "alertId": self.alert_id,
            "assetId": self.asset_id,
            "alertType": self.alert_type,
            "severity": self.severity,
            "riskScore": self.risk_score,
            "timestamp": self.timestamp,
            "description": self.description,
            "acknowledged": self.acknowledged,
        }


# ──────────────────────────────────────────────────────────────────────────────
# CLASS: DataValidator
# ──────────────────────────────────────────────────────────────────────────────

class DataValidator:
    """Validates generated synthetic data for quality and consistency."""

    @staticmethod
    def validate_ohlcv(df: pd.DataFrame) -> Tuple[bool, List[str]]:
        """Check OHLCV invariants: high >= close >= low, volume > 0, etc."""
        errors = []
        if "high" in df.columns and "low" in df.columns:
            if (df["high"] < df["low"]).any():
                errors.append("HIGH < LOW violations found")
            if "close" in df.columns:
                if (df["close"] > df["high"]).any():
                    errors.append("CLOSE > HIGH violations")
                if (df["close"] < df["low"]).any():
                    errors.append("CLOSE < LOW violations")
        if "volume" in df.columns:
            if (df["volume"] < 0).any():
                errors.append("Negative volume values found")
        if "close" in df.columns:
            if df["close"].isna().any():
                errors.append("NaN close prices found")
            if (df["close"] <= 0).any():
                errors.append("Non-positive close prices found")
        return len(errors) == 0, errors

    @staticmethod
    def validate_sentiment(df: pd.DataFrame) -> Tuple[bool, List[str]]:
        """Validate sentiment scores are in [-1, 1] range."""
        errors = []
        if "sentiment_score" in df.columns:
            if (df["sentiment_score"] > 1.0).any():
                errors.append("Sentiment > 1.0 found")
            if (df["sentiment_score"] < -1.0).any():
                errors.append("Sentiment < -1.0 found")
        if "follower_count" in df.columns:
            if (df["follower_count"] < 0).any():
                errors.append("Negative follower count")
        return len(errors) == 0, errors

    @staticmethod
    def validate_graph_data(graph_dict: dict) -> Tuple[bool, List[str]]:
        """Check graph data has required structure."""
        errors = []
        if "nodes" not in graph_dict:
            errors.append("Missing 'nodes' key")
        if "edges" not in graph_dict:
            errors.append("Missing 'edges' key")
        if graph_dict.get("nodes"):
            sample = graph_dict["nodes"][0]
            if "id" not in sample:
                errors.append("Node missing 'id' field")
        return len(errors) == 0, errors


# ──────────────────────────────────────────────────────────────────────────────
# CLASS: DatasetManifestBuilder
# ──────────────────────────────────────────────────────────────────────────────

class DatasetManifestBuilder:
    """Builds a manifest describing the generated dataset for reproducibility."""

    def __init__(self, module_name: str = "EP-GNN"):
        self.manifest = {
            "module": module_name,
            "full_name": "Emotion Propagation Graph Neural Network",
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "random_seed": 42,
            "files": [],
            "statistics": {},
            "data_hash": None,
        }

    def register_file(self, filepath: str, n_rows: int, description: str) -> None:
        self.manifest["files"].append({
            "path": filepath,
            "n_rows": n_rows,
            "description": description,
            "checksum": self._checksum(filepath),
        })

    def _checksum(self, filepath: str) -> Optional[str]:
        if not os.path.exists(filepath):
            return None
        h = hashlib.md5()
        with open(filepath, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                h.update(chunk)
        return h.hexdigest()

    def add_statistics(self, key: str, value: Any) -> None:
        self.manifest["statistics"][key] = value

    def save(self, output_path: str = "outputs/ep_gnn_data/manifest.json") -> None:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(self.manifest, f, indent=2, default=str)
        print(f"  Manifest saved → {output_path}")


# ──────────────────────────────────────────────────────────────────────────────
# CLASS: FeatureEngineeringEngine
# ──────────────────────────────────────────────────────────────────────────────

class FeatureEngineeringEngine:
    """
    Computes EP-GNN-specific features from raw synthetic data.
    Features are designed to capture manipulation signatures specific
    to the Emotion Propagation Graph Neural Network approach.
    """

    FEATURE_GROUPS = {
        "price_based": [
            "log_return", "rolling_vol_5", "rolling_vol_20",
            "momentum_5", "momentum_20", "price_range_pct",
        ],
        "volume_based": [
            "volume_log", "volume_zscore", "vol_ma_ratio",
            "vwap_deviation", "volume_spike_flag",
        ],
        "microstructure": [
            "bid_ask_spread", "order_imbalance", "depth_total_log",
            "mid_price_move", "trade_intensity",
        ],
        "sentiment": [
            "avg_sentiment_1h", "sentiment_velocity", "sentiment_vol",
            "coordinated_post_ratio", "influencer_weighted_sentiment",
        ],
        "graph": [
            "degree_centrality", "betweenness_centrality",
            "clustering_coeff", "pagerank", "corr_neighborhood_avg",
        ],
    }

    def __init__(self):
        self.computed_features = {}

    def compute_price_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """Compute price-based features."""
        df = df.copy()
        df["log_return"]      = np.log(df["close"] / df["close"].shift(1)).fillna(0)
        df["rolling_vol_5"]   = df["log_return"].rolling(5).std().fillna(0)
        df["rolling_vol_20"]  = df["log_return"].rolling(20).std().fillna(0)
        df["momentum_5"]      = df["close"].pct_change(5).fillna(0)
        df["momentum_20"]     = df["close"].pct_change(20).fillna(0)
        df["price_range_pct"] = ((df["high"] - df["low"]) / df["close"]).fillna(0)
        return df

    def compute_volume_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """Compute volume-based anomaly features."""
        df = df.copy()
        df["volume_log"]    = np.log1p(df["volume"])
        vol_mean = df["volume"].rolling(20).mean().replace(0, 1)
        vol_std  = df["volume"].rolling(20).std().replace(0, 1)
        df["volume_zscore"] = ((df["volume"] - vol_mean) / vol_std).fillna(0)
        df["vol_ma_ratio"]  = (df["volume"] / vol_mean.replace(0, 1)).fillna(1)
        # VWAP deviation
        df["vwap"] = (df["close"] * df["volume"]).cumsum() / df["volume"].cumsum().replace(0, 1)
        df["vwap_deviation"]    = ((df["close"] - df["vwap"]) / df["vwap"].replace(0, 1)).fillna(0)
        df["volume_spike_flag"] = (df["volume_zscore"].abs() > 3.0).astype(int)
        return df

    def compute_sentiment_features(self, price_df: pd.DataFrame,
                                   sent_df: pd.DataFrame) -> pd.DataFrame:
        """Merge sentiment features into price dataframe."""
        sent_agg = sent_df.groupby("asset_id").agg(
            avg_sentiment_1h       = ("sentiment_score", "mean"),
            sentiment_vol          = ("sentiment_score", "std"),
            coordinated_post_ratio = ("is_coordinated", "mean"),
        ).reset_index()
        merged = price_df.merge(sent_agg, on="asset_id", how="left")
        merged["avg_sentiment_1h"].fillna(0, inplace=True)
        merged["sentiment_vol"].fillna(0, inplace=True)
        merged["coordinated_post_ratio"].fillna(0, inplace=True)
        merged["sentiment_velocity"] = merged.groupby("asset_id")["avg_sentiment_1h"].diff().fillna(0)
        return merged

    def compute_graph_features(self, G) -> dict:
        """Compute graph-theoretic features for each asset node."""
        import networkx as nx
        features = {}
        degree_centrality      = nx.degree_centrality(G)
        try:
            betweenness_centrality = nx.betweenness_centrality(G, normalized=True)
        except Exception:
            betweenness_centrality = {n: 0.0 for n in G.nodes()}
        try:
            clustering             = nx.clustering(G.to_undirected())
        except Exception:
            clustering             = {n: 0.0 for n in G.nodes()}
        try:
            pagerank               = nx.pagerank(G, alpha=0.85)
        except Exception:
            pagerank               = {n: 1.0/G.number_of_nodes() for n in G.nodes()}

        for node in G.nodes():
            features[node] = {
                "degree_centrality":     degree_centrality.get(node, 0),
                "betweenness_centrality": betweenness_centrality.get(node, 0),
                "clustering_coeff":      clustering.get(node, 0),
                "pagerank":              pagerank.get(node, 0),
            }
        return features

    def build_feature_matrix(self, price_df: pd.DataFrame,
                             sent_df: pd.DataFrame,
                             graph_features: dict) -> pd.DataFrame:
        """Assemble final feature matrix for GNN training."""
        enriched = self.compute_price_features(price_df)
        enriched = self.compute_volume_features(enriched)
        enriched = self.compute_sentiment_features(enriched, sent_df)

        # Add graph features per asset
        for feat_name in ["degree_centrality", "betweenness_centrality",
                          "clustering_coeff", "pagerank"]:
            enriched[feat_name] = enriched["asset_id"].map(
                {k: v.get(feat_name, 0) for k, v in graph_features.items()}
            ).fillna(0)

        feature_cols = (
            ["log_return", "rolling_vol_5", "rolling_vol_20",
             "momentum_5", "momentum_20", "price_range_pct",
             "volume_log", "volume_zscore", "vol_ma_ratio",
             "vwap_deviation", "volume_spike_flag",
             "avg_sentiment_1h", "sentiment_vol",
             "coordinated_post_ratio", "sentiment_velocity",
             "degree_centrality", "betweenness_centrality",
             "clustering_coeff", "pagerank"]
        )
        existing_cols = [c for c in feature_cols if c in enriched.columns]
        return enriched[["asset_id", "timestamp", "is_manipulation"] + existing_cols]


# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────

def main():
    print(f"\nEP-GNN DataModel Engine Initialized")
    print(f"  Feature groups: {list(FeatureEngineeringEngine.FEATURE_GROUPS.keys())}")

    validator = DataValidator()
    manifest  = DatasetManifestBuilder("EP-GNN")
    feat_eng  = FeatureEngineeringEngine()

    # Test data schema
    sample_asset = AssetRecord(
        asset_id="ASSET_001",
        sector="Technology",
        market_cap_tier="large",
        exchange="NASDAQ",
        listing_date="2020-01-15",
    )
    print(f"  Sample Asset neo4j props: {sample_asset.to_neo4j_props()}")

    sample_alert = RiskAlertRecord(
        alert_id="ALERT_001",
        asset_id="ASSET_001",
        alert_type="pump_and_dump",
        severity="high",
        risk_score=0.87,
        timestamp=datetime.utcnow().isoformat(),
        description="Coordinated social media pump detected with volume anomaly",
        supporting_signals=["SIGNAL_001", "SIGNAL_002"],
    )
    print(f"  Sample Alert: {sample_alert.alert_type} | severity={sample_alert.severity}")

    manifest.add_statistics("module", "EP-GNN")
    manifest.add_statistics("feature_count",
                             sum(len(v) for v in FeatureEngineeringEngine.FEATURE_GROUPS.values()))
    manifest.save()
    print("  DataModel Engine test complete.")

if __name__ == "__main__":
    main()
